### ISSUE TITLE
Link with prebuilt shared object?

### ISSUE THREAD

**Issue by sliceofcode** [byteandahalf/GenericLauncher#12]
Hi there.
I have an armeabi-v7a shared object- `liblua.so`, but I cannot figure out how to link it with the rest of the libraries; it just reports undefined references to methods in the shared object that are obviously not being linked.

Any advice on linking it involving Android.mk/Application.mk?

**Comment by sliceofcode** [comment]
NAH

**Comment by byteandahalf** [comment]
I'm guessing you figured it out?

**Comment by sliceofcode** [comment]
@byteandahalf Nope, but I found out how to do it another way.
