### ISSUE TITLE
Bug when building GenericLauncher with AIDE

### ISSUE THREAD

**Issue by jose-vm** [byteandahalf/GenericLauncher#2]
I tried building this project with AIDE, and it says they are mistakes on this project. I tried to fix them, but that didn't helped.

**Comment by artus9033** [comment]
Reproduced the bug.

**Comment by sliceofcode** [comment]
I wouldn't recommend using AIDE as your primary development environment, typing on a computer is much faster and it is harder to debug problems on AIDE because it is significantly different from the usual Android SDK and NDK.

**Comment by artus9033** [comment]
Yes, but aide is helpful. I fixed the bug. Move the class with error to src/com/mojang/minecraftpe.

**Comment by artus9033** [comment]
@sliceofcode, you can close the issue.

**Comment by sliceofcode** [comment]
This isn't my issue.

**Comment by artus9033** [comment]
So whose issue is this?

**Comment by sliceofcode** [comment]
@jose-vm

**Comment by artus9033** [comment]
Ok, sorry.
