### ISSUE TITLE
I'm confused as to how to compile

### ISSUE THREAD

**Issue by TheDiamondYT1** [byteandahalf/GenericLauncher#25]
Why do we need GenericLauncher-App, can't we do without it? How to compile

**Comment by sliceofcode** [comment]
```sh
$ ndk-build
$ ant clean debug
```
You shouldn't be using AIDE.

**Comment by TheDiamondYT1** [comment]
Didn't you make a video showing how to compile on AIDE?

**Comment by sliceofcode** [comment]
Yes, but that was long ago. I was dumb enough to be using it, but that was when a computer wasn't available for me.

**Comment by jose-vm** [comment]
AIDE still works for me :P

**Comment by malucard** [comment]
Is there any way to build with Android Studio?
