### ISSUE TITLE
i

### ISSUE THREAD

**Issue by MasterCakeMan12** [byteandahalf/GenericLauncher#9]
I dont really know what to do with this.
Soo what do i do with it?

**Comment by sliceofcode** [comment]
@MasterCakeMan12 Do you know Java and C++?

**Comment by MasterCakeMan12** [comment]
Uhhh would it be bad if I said... no xD

**Comment by sliceofcode** [comment]
@MasterCakeMan12 Yes. You need to know those to actually do **anything** with GenericLauncher.

**Comment by MasterCakeMan12** [comment]
Ohh ok. Yeah... I know *nothing* about c++ but a bit about java
